services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=8U8T5K8U
      - POSTGRES_DB=german_credit_risk
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./Backend
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:8U8T5K8U@db:5432/german_credit_risk
    depends_on:
      - db

  frontend:
    build: ./Frontend
    container_name: streamlit_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend

volumes:
  postgres_data:
